print("What type of stat would you like?")
print("1. Best Goal Scorer")
print("2. Best Playmaker")
print("3. Best Offensive Decencemen")
print("4. Best +/-")
print("5. Most Time on Ice")
print("6. Most Penalty Minutes")
print("8. Best Overall Defenceman")
print("9. Best Overall Forward")
print("")
stat_type = int(input("Type the number of which stat you want: "))
print("")
print("Which position?")
print("1. Center")
print("2. Left Wing")
print("3. Right Wing")
print("4. Defence")
print("5. Any")
print("")
position = int(input("Type the number of which position you want: "))
print("")
print("Which age range?")
print("1. 18-23")
print("2. 24-29")
print("3. 30-35")
print("4. 36-40")
print("5. 40+")
print("6. Any")
print("")
age_range = int(input("Type the number of which age range you want: "))
print("")
print("Finally, which team do you want?")
print("1. ANA")
print("2. ARI")
print("3. BOS")
print("4. BUF")
print("5. CAR")
print("6. CBJ")
print("7. CGY")
print("8. CHI")
print("9. COL")
print("10. DAL")
print("11. DET")
print("12. EDM")
print("13. FLO")
print("14. MIN")
print("15. LAK")
print("16. MTL")
print("17. NSH")
print("18. NJD")
print("19. NYI")
print("20. NYR")
print("21. OTT")
print("22. PHI")
print("23. PIT")
print("24. SJS")
print("25. STL")
print("26. TBL")
print("27. TOR")
print("28. VAN")
print("29. VEG")
print("30. WSH")
print("31. WPG")
print("32. Any")
print("")
team = int(input("Type the number of which team you want: "))